const KEYS={app:'savePoint.unified.v2',oldApp:'savePoint.unified.v1',pb:'pb-race-data',street:'everyStreetHarbin.v1',story:'life-galgame-v1'};
const ROAD_URLS=['./data/harbin-roads.json','https://dongdong-web.github.io/citymap/data/harbin-roads.json'];
const BIRTH={y:2001,m:8,d:11},$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const id=()=>crypto.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2),pad=n=>String(n).padStart(2,'0');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dk=(v=new Date())=>{let d=v instanceof Date?v:new Date(v);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const fmtTime=t=>new Date(t).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'});
const fmtMs=ms=>{let s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor(s%3600/60),ss=s%60;return h?`${pad(h)}:${pad(m)}:${pad(ss)}`:`${pad(m)}:${pad(ss)}`};
const cnDate=(v=new Date())=>{let d=v instanceof Date?v:new Date(v);return `${d.getFullYear()} 年 ${d.getMonth()+1} 月 ${d.getDate()} 日`};
let db=load(),view='home',timerTick=null,map=null,mapLines=[],roads=[],currentRoad=null,streetQuery='',storyFilter='ALL',storyTag='',storyQuery='',pbMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),pbSelected=dk();

function fresh(){return {version:2,pb:{challenges:[],activeTimer:null},street:{done:[],visits:{}},stories:[],notes:[],todos:[],settings:{legacyImported:false}}}
function normalize(x){let n=fresh();if(!x||typeof x!=='object')return n;n.pb=x.pb||n.pb;n.street=x.street||n.street;if(!Array.isArray(n.street.done))n.street.done=[];n.street.visits=n.street.visits||{};n.stories=Array.isArray(x.stories)?x.stories:[];n.notes=Array.isArray(x.notes)?x.notes:Array.isArray(x.saves)?x.saves.map(s=>({id:s.id||id(),text:`${s.title||''}${s.detail?' · '+s.detail:''}`,at:s.at||new Date().toISOString()})):[];n.todos=normalizeTodos(x.todos);n.settings={...n.settings,...(x.settings||{})};return n}
function load(){try{let raw=localStorage.getItem(KEYS.app);if(raw)return normalize(JSON.parse(raw));let old=localStorage.getItem(KEYS.oldApp);if(old){let n=normalize(JSON.parse(old));localStorage.setItem(KEYS.app,JSON.stringify(n));return n}}catch{}return fresh()}
function save(){db.version=2;localStorage.setItem(KEYS.app,JSON.stringify(db))}
function normPB(raw){if(!raw||!Array.isArray(raw.challenges))return null;return {challenges:raw.challenges.map(c=>({...c,records:Array.isArray(c.records)?c.records:[],completedCount:Math.max(c.completedCount||0,c.records?.length||0),scoring:c.scoring||{type:'duration',direction:'lower',unit:'ms'}})),activeTimer:raw.activeTimer||null}}
function migrateLegacy(force=false){if(db.settings.legacyImported&&!force)return false;let found=false;
 try{let n=normPB(JSON.parse(localStorage.getItem(KEYS.pb)||'null'));if(n&&n.challenges.length){db.pb=n;found=true}}catch{}
 try{let a=JSON.parse(localStorage.getItem(KEYS.street)||'null');if(Array.isArray(a)&&a.length){db.street.done=[...new Set(a)];found=true}}catch{}
 try{let a=JSON.parse(localStorage.getItem(KEYS.story)||'null');if(Array.isArray(a)&&a.length){db.stories=a;found=true}}catch{}
 db.settings.legacyImported=true;save();return found}
migrateLegacy();

function score(c,v){return c.scoring?.type==='number'?`${Math.round(v)} 次`:fmtMs(v)}
function best(c){return (c.records||[]).reduce((b,r)=>!b||(c.scoring?.direction==='higher'?r.value>b.value:r.value<b.value)?r:b,null)}
function isPB(c,r){return best(c)?.id===r.id}
function dayNumber(){let a=Date.UTC(BIRTH.y,BIRTH.m-1,BIRTH.d),d=new Date(),b=Date.UTC(d.getFullYear(),d.getMonth(),d.getDate());return Math.floor((b-a)/86400000)+1}
function events(){
 let a=[];
 db.pb.challenges.forEach(c=>(c.records||[]).forEach(r=>a.push({id:'pb:'+r.id,type:'行动',title:c.name,detail:`${score(c,r.value)}${isPB(c,r)?' · PB':''}`,at:new Date(r.completedAt).toISOString()})));
 Object.entries(db.street.visits||{}).forEach(([rid,v])=>{if(v?.at)a.push({id:'st:'+rid,type:'探索',title:v.name||rid,detail:'已走过',at:v.at})});
 db.stories.forEach(s=>a.push({id:'story:'+s.id,type:'剧情',title:s.title,detail:s.outcome?'已有结局':'未完待续',at:s.updatedAt||s.createdAt}));
 db.notes.forEach(n=>a.push({id:'note:'+n.id,type:'手记',title:n.text,detail:'',at:n.at}));
 return a.sort((x,y)=>new Date(y.at)-new Date(x.at))
}
function nav(v){view=v;clearInterval(timerTick);if(map){try{map.remove()}catch{}map=null}$$('.rail nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$('.rail').classList.remove('open');render()}
$$('.rail nav button').forEach(b=>b.onclick=()=>nav(b.dataset.view));$('#menuBtn').onclick=()=>$('.rail').classList.toggle('open');
function clock(){let d=new Date();$('#clock').textContent=`${pad(d.getHours())}:${pad(d.getMinutes())}`}clock();setInterval(clock,30000);
function render(){({home,pb,street,story,timeline,archive}[view]||home)()}

function home(){
 let now=new Date(),ev=events();
 $('#view').innerHTML=`<div class="page"><div class="home-hero"><div class="hero-main"><div class="kicker">人生纪日</div><div class="day"><small>第</small>${dayNumber()}<small>日</small></div><div class="since">自 二〇〇一年八月十一日 以来</div><div class="hero-copy">${ev.some(e=>dk(e.at)===dk())?'今日已有存档。':'一些平凡的日子，也值得被记住。'}<br><small>${ev[0]?`最近：${esc(ev[0].title)}`:'去做一件事，走一条街，或记下一次选择。'}</small></div><button class="seal-btn" id="quickNote">记一笔</button></div><aside class="hero-side"><div class="kicker">今日</div><h2 class="display">${cnDate(now)}</h2><div class="summary"><div class="summary-row"><span>行动挑战</span><b>${db.pb.challenges.length}</b></div><div class="summary-row"><span>已走街道</span><b>${db.street.done.length}</b></div><div class="summary-row"><span>人生剧情</span><b>${db.stories.length}</b></div></div>${memoCalendar(ev)}</aside></div><div class="modules"><button class="module" data-go="pb"><span class="n">一</span><h3>行动</h3><p>和昨天的自己比赛</p></button><button class="module" data-go="street"><span class="n">二</span><h3>探索</h3><p>走遍哈尔滨的每一条街</p></button><button class="module" data-go="story"><span class="n">三</span><h3>剧情</h3><p>记住选择，留住经验</p></button></div><div class="recent-home"><div class="section-title"><div><div class="kicker">近日存档</div><h1>最近发生</h1></div><button class="btn" id="allTimeline">查看时间线</button></div>${eventRows(ev.slice(0,6))}</div></div>`;
 $$('.module').forEach(x=>x.onclick=()=>nav(x.dataset.go));$('#allTimeline').onclick=()=>nav('timeline');$('#quickNote').onclick=quickNote;bindMemoCalendar()
}
function quickNote(){modal(`<h2>记一笔</h2><form id="qnf"><div class="field"><label>今天值得留下什么？</label><textarea name="text" maxlength="280" required autofocus></textarea></div><div class="actions"><button class="btn dark">存档</button><button type="button" class="btn" id="qx">取消</button></div></form>`);$('#qx').onclick=closeModal;$('#qnf').onsubmit=e=>{e.preventDefault();let t=new FormData(e.target).get('text').trim();if(t)db.notes.push({id:id(),text:t,at:new Date().toISOString()});save();closeModal();home()}}

function pb(){
 let cs=[...db.pb.challenges].sort((a,b)=>(b.completedCount||0)-(a.completedCount||0)||b.updatedAt-a.updatedAt),recs=cs.reduce((n,c)=>n+(c.records?.length||0),0);
 $('#view').innerHTML=`<div class="page"><div class="section-title"><div><div class="kicker">行动 · 与昨天的自己比赛</div><h1>行动</h1></div><div class="actions"><button class="btn" id="pbCalendar">节律日历</button><button class="btn dark" id="newChallenge">新建挑战</button></div></div><div class="metric-grid"><div class="metric"><strong>${cs.length}</strong><span>挑战</span></div><div class="metric"><strong>${recs}</strong><span>完成记录</span></div><div class="metric"><strong>${db.pb.activeTimer?'进行中':'待开始'}</strong><span>当前状态</span></div></div><div class="list">${cs.length?cs.map(c=>`<div class="row"><div class="date">${c.completedCount||c.records?.length||0} 次</div><div><h3>${esc(c.name)}</h3><p>${c.records?.length?'个人最佳 '+score(c,best(c).value):'暂无记录'}${c.standard?' · '+esc(c.standard):''}</p>${practiceProgress(c,true)}</div><button class="btn" data-c="${c.id}">${db.pb.activeTimer?.challengeId===c.id?'继续':'打开'}</button></div>`).join(''):'<div class="empty">还没有挑战。把一件重复却总不想开始的事，变成和自己的比赛。</div>'}</div></div>`;
 $('#newChallenge').onclick=()=>challengeForm();$('#pbCalendar').onclick=pbCalendarView;$$('[data-c]').forEach(b=>b.onclick=()=>challengeDetail(b.dataset.c))
}
function challengeForm(c=null){
 let mode=c?.scoring?.type==='number'?'more':c?.scoring?.direction==='higher'?'longer':'faster';
 modal(`<h2>${c?'编辑挑战':'新建挑战'}</h2><form id="cf" class="form"><div class="field"><label>挑战名称</label><input name="name" maxlength="80" required value="${esc(c?.name||'')}"></div><div class="field"><label>完成标准</label><input name="standard" maxlength="280" value="${esc(c?.standard||'')}"></div><div class="field"><label>计分方式${c&&(c.records?.length||db.pb.activeTimer?.challengeId===c.id)?'（已有记录或计时中，保留原方式）':''}</label><select name="mode" ${c&&(c.records?.length||db.pb.activeTimer?.challengeId===c.id)?'disabled':''}><option value="faster" ${mode==='faster'?'selected':''}>计时 · 越快越好</option><option value="longer" ${mode==='longer'?'selected':''}>计时 · 越久越好</option><option value="more" ${mode==='more'?'selected':''}>次数 · 越多越好</option></select></div><div class="actions"><button class="btn dark">保存</button><button type="button" class="btn" id="cx">取消</button>${c?'<button type="button" class="btn danger" id="delC">删除挑战</button>':''}</div></form>`);
 $('#cx').onclick=closeModal;if(c)$('#delC').onclick=()=>{if(confirm(`删除“${c.name}”及其全部成绩？`)){db.pb.challenges=db.pb.challenges.filter(x=>x.id!==c.id);if(db.pb.activeTimer?.challengeId===c.id)db.pb.activeTimer=null;save();closeModal();pb()}};
 $('#cf').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),m=f.get('mode')||mode,now=Date.now(),x=c||{id:id(),records:[],createdAt:now,completedCount:0};x.name=f.get('name').trim();x.standard=f.get('standard').trim();x.updatedAt=now;x.scoring=m==='more'?{type:'number',direction:'higher',unit:'次'}:{type:'duration',direction:m==='longer'?'higher':'lower',unit:'ms'};if(!c)db.pb.challenges.push(x);save();closeModal();if(c)pb();else{challengeDetail(x.id);window.scrollTo(0,0)}}
}
function challengeDetail(cid){
 clearInterval(timerTick);
 let c=db.pb.challenges.find(x=>x.id===cid);if(!c)return nav('pb');let run=db.pb.activeTimer?.challengeId===cid,last=c.records?.at(-1),b=best(c);
 $('#view').innerHTML=`<div class="page"><button class="btn" id="pbBack">← 行动</button><div class="detail-head"><div class="kicker">个人挑战</div><h1 class="display">${esc(c.name)}</h1><p>${esc(c.standard||'只和上一次的自己比赛。')}</p></div><div class="pb-focus"><div><div class="kicker">${run?(db.pb.activeTimer.stoppedAt?'计时已结束 · 待填写次数':'正在进行'):'本次用时'}</div><div class="timer" id="timer">${run?fmtMs((db.pb.activeTimer.stoppedAt||Date.now())-db.pb.activeTimer.startedAt):'00:00'}</div><div class="timer-actions"><button class="btn dark" id="timerBtn">${run?(db.pb.activeTimer.stoppedAt?'填写次数':'完成'):'开始'}</button>${run?'<button class="btn" id="cancelTimer">取消本次</button>':c.scoring.type==='number'?'<button class="btn" id="numScore">补录成绩</button>':''}</div></div><div class="pb-stats"><div><span>个人最佳</span><b>${b?score(c,b.value):'—'}</b></div><div><span>上一次</span><b>${last?score(c,last.value):'—'}</b></div><div><span>累计完成</span><b>${c.completedCount||c.records.length} 次</b></div></div></div>${practiceProgress(c)}<div class="section-title"><div><div class="kicker">往日记录</div><h1>历史</h1></div><button class="btn" id="editC">编辑挑战</button></div><div class="list">${[...(c.records||[])].reverse().map(r=>`<div class="row"><div class="date">${dk(r.completedAt).slice(5).replace('-','.')}</div><div><h3>${score(c,r.value)} ${isPB(c,r)?'<em class="pbmark">PB</em>':''}</h3><p>${fmtTime(r.completedAt)}${c.scoring.type==='number'&&r.durationMs?' · 用时 '+practiceTime(r.durationMs):''}</p></div><button class="btn danger small" data-delr="${r.id}">删除</button></div>`).join('')||'<div class="empty">暂无记录。</div>'}</div></div>`;
 $('#pbBack').onclick=()=>nav('pb');$('#editC').onclick=()=>challengeForm(c);$$('[data-delr]').forEach(x=>x.onclick=()=>{if(confirm('删除这条成绩？')){c.records=c.records.filter(r=>r.id!==x.dataset.delr);c.completedCount=Math.max(c.records.length,(c.completedCount||1)-1);save();challengeDetail(cid)}});
 if($('#numScore'))$('#numScore').onclick=()=>numberScore(c);
 $('#timerBtn').onclick=()=>run?(c.scoring.type==='number'?finishNumberTimer(c):finishTimer(c)):startTimer(c);
 if(run){$('#cancelTimer').onclick=()=>{db.pb.activeTimer=null;save();challengeDetail(cid)};if(!db.pb.activeTimer.stoppedAt)timerTick=setInterval(()=>{let e=$('#timer');if(e&&db.pb.activeTimer)e.textContent=fmtMs(Date.now()-db.pb.activeTimer.startedAt)},200)}

}
function startTimer(c){if(db.pb.activeTimer&&db.pb.activeTimer.challengeId!==c.id)return alert('已有另一项挑战正在计时。');db.pb.activeTimer={challengeId:c.id,startedAt:Date.now()};save();challengeDetail(c.id)}
function finishTimer(c){let v=Date.now()-db.pb.activeTimer.startedAt;c.records.push({id:id(),value:v,durationMs:v,completedAt:Date.now()});c.completedCount=(c.completedCount||0)+1;db.pb.activeTimer=null;save();challengeDetail(c.id)}
function finishNumberTimer(c){let session=db.pb.activeTimer;if(!session||session.challengeId!==c.id)return;if(!session.stoppedAt){session.stoppedAt=Date.now();save()}challengeDetail(c.id);numberScore(c,session)}
function numberScore(c,session=null){
 let duration=session?Math.max(0,session.stoppedAt-session.startedAt):null;
 modal(`<h2>${session?'完成挑战':'补录成绩'}</h2><form id="nf"><div class="field"><label for="numberResult">${esc(c.name)} · 本次完成次数</label><input id="numberResult" type="number" min="0" step="1" name="v" required autofocus></div>${session?`<p>本次用时：${practiceTime(duration)}，保存后自动计入累计时长。</p>`:'<div class="field"><label for="practiceMinutes">本次用时（分钟，可选）</label><input id="practiceMinutes" type="number" min="0" step="0.01" name="minutes" placeholder="用于累计一万小时进度"></div>'}<p class="muted">${best(c)?'个人最佳：'+score(c,best(c).value)+'，次数更多即可突破 PB。':'第一次成绩将成为你的个人最佳。'}</p><div class="actions"><button class="btn dark">保存</button><button type="button" class="btn" id="nx">${session?'稍后填写':'取消'}</button></div></form>`);
 $('#nx').onclick=closeModal;$('#nf').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target),v=Number(f.get('v')),minutes=Number(f.get('minutes'));if(!Number.isFinite(v)||v<0||!Number.isInteger(v)||!Number.isFinite(minutes)||minutes<0||!Number.isFinite(minutes*60000))return;if(session&&db.pb.activeTimer!==session)return;c.records.push({id:id(),value:v,durationMs:session?duration:Math.round(minutes*60000),completedAt:session?session.stoppedAt:Date.now()});c.completedCount=(c.completedCount||0)+1;if(session)db.pb.activeTimer=null;save();closeModal();challengeDetail(c.id)}
}

function pbEntries(k){let a=[];db.pb.challenges.forEach(c=>(c.records||[]).forEach(r=>{if(dk(r.completedAt)===k)a.push({c,r})}));return a.sort((x,y)=>x.r.completedAt-y.r.completedAt)}
function pbCalendarView(){
 let y=pbMonth.getFullYear(),m=pbMonth.getMonth(),today=new Date(),first=(new Date(y,m,1).getDay()+6)%7,n=new Date(y,m+1,0).getDate(),counts={};db.pb.challenges.forEach(c=>(c.records||[]).forEach(r=>{let k=dk(r.completedAt);counts[k]=(counts[k]||0)+1}));
 let cells='';for(let i=0;i<first;i++)cells+='<span class="cal blank"></span>';for(let d=1;d<=n;d++){let k=`${y}-${pad(m+1)}-${pad(d)}`;cells+=`<button class="cal ${counts[k]?'has':''} ${k===pbSelected?'selected':''} ${k===dk()?'today':''}" data-day="${k}"><b>${d}</b>${counts[k]?`<i>${counts[k]}</i>`:''}</button>`}
 let ents=pbEntries(pbSelected);
 $('#view').innerHTML=`<div class="page"><div class="section-title"><div><div class="kicker">行动节律</div><h1>${y} 年 ${m+1} 月</h1></div><div class="actions"><button class="btn" id="prevM">上月</button><button class="btn" id="nextM">下月</button><button class="btn" id="backP">返回行动</button></div></div><div class="weekheads">${['一','二','三','四','五','六','日'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar">${cells}</div><div class="section-title dayrecords"><div><div class="kicker">当日记录</div><h1>${pbSelected}</h1></div></div><div class="list">${ents.length?ents.map(({c,r})=>`<div class="row"><div class="date">${fmtTime(r.completedAt)}</div><div><h3>${esc(c.name)}</h3><p>${score(c,r.value)} ${isPB(c,r)?'· PB':''}</p></div></div>`).join(''):'<div class="empty">这一天没有 PB 记录。</div>'}</div></div>`;
 $('#backP').onclick=()=>nav('pb');$('#prevM').onclick=()=>{pbMonth=new Date(y,m-1,1);pbSelected=`${pbMonth.getFullYear()}-${pad(pbMonth.getMonth()+1)}-01`;pbCalendarView()};$('#nextM').onclick=()=>{let x=new Date(y,m+1,1),cur=new Date(today.getFullYear(),today.getMonth(),1);if(x<=cur){pbMonth=x;pbSelected=x.getFullYear()+'-'+pad(x.getMonth()+1)+'-01';pbCalendarView()}};$$('[data-day]').forEach(b=>b.onclick=()=>{pbSelected=b.dataset.day;pbCalendarView()})
}

async function ensureRoads(){if(roads.length)return true;for(let u of ROAD_URLS){try{let r=await fetch(u);if(!r.ok)continue;let j=await r.json();roads=j.roads||[];if(roads.length)return true}catch{}}return false}
function street(){
 $('#view').innerHTML=`<div class="page"><div class="section-title"><div><div class="kicker">探索 · 哈尔滨</div><h1>走遍哈尔滨</h1></div><div class="actions"><button class="btn" id="catalog">街道图鉴</button><b id="streetPct">—</b></div></div><div class="street-layout"><div id="map" class="map"></div><aside class="street-panel"><div class="kicker">今日随机街道</div><div class="road-name" id="roadName">正在读取路网…</div><p id="roadMeta">从尚未探索的道路中随机抽取。</p><div class="progress"><i id="streetBar"></i></div><div class="actions"><button class="btn dark" id="randomRoad">换一条</button><button class="btn" id="doneRoad" disabled>标记为已走</button><button class="btn" id="amap" disabled>高德查看</button></div></aside></div><div class="metric-grid"><div class="metric"><strong id="doneRoads">${db.street.done.length}</strong><span>已走街道</span></div><div class="metric"><strong id="leftRoads">—</strong><span>等待探索</span></div><div class="metric"><strong id="walkKm">—</strong><span>已打卡道路总长度</span></div></div></div>`;
 initStreet();$('#catalog').onclick=streetCatalog
}
async function initStreet(){
 if(!await ensureRoads()){setText('#roadName','路网读取失败');setText('#roadMeta','请把原 citymap/data/harbin-roads.json 复制到本项目 data/ 目录。');return}
 renderStreetStats();if(window.L){map=L.map('map').setView([45.75,126.63],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map)}
 $('#randomRoad').onclick=randomRoad;$('#doneRoad').onclick=toggleRoad;$('#amap').onclick=()=>currentRoad&&window.open('https://uri.amap.com/search?keyword='+encodeURIComponent('哈尔滨 '+currentRoad.name)+'&city=哈尔滨&view=map','_blank');randomRoad()
}
function setText(sel,t){let e=$(sel);if(e)e.textContent=t}
function renderStreetStats(){let done=new Set(db.street.done),pct=roads.length?done.size/roads.length*100:0;setText('#streetPct',pct.toFixed(pct<10?1:0)+'%');if($('#streetBar'))$('#streetBar').style.width=pct+'%';setText('#doneRoads',done.size);setText('#leftRoads',Math.max(0,roads.length-done.size));let m=roads.filter(r=>done.has(r.id)).reduce((s,r)=>s+(r.lengthM||0),0);setText('#walkKm',(m/1000).toFixed(1)+' km')}
function randomRoad(){let d=new Set(db.street.done),pool=roads.filter(r=>!d.has(r.id)&&r.id!==currentRoad?.id);if(!pool.length)pool=roads;if(pool.length)showRoad(pool[Math.floor(Math.random()*pool.length)])}
function showRoad(r){currentRoad=r;setText('#roadName',r.name);setText('#roadMeta',`约 ${r.lengthM<1000?Math.round(r.lengthM)+' 米':(r.lengthM/1000).toFixed(1)+' 公里'} · ${r.segments.length} 个路段 · ${db.street.done.includes(r.id)?'已探索':'未探索'}`);$('#doneRoad').disabled=false;$('#amap').disabled=false;setText('#doneRoad',db.street.done.includes(r.id)?'取消打卡':'标记为已走');if(map){mapLines.forEach(x=>map.removeLayer(x));mapLines=[];let b=[];r.segments.forEach(seg=>{let ll=seg.map(p=>[p[1],p[0]]);b.push(...ll);mapLines.push(L.polyline(ll,{weight:5,opacity:.85,color:'#17202a'}).addTo(map))});if(b.length)map.fitBounds(b,{padding:[25,25],maxZoom:16})}}
function toggleRoad(){if(!currentRoad)return;let i=db.street.done.indexOf(currentRoad.id);if(i>=0){db.street.done.splice(i,1);delete db.street.visits[currentRoad.id]}else{db.street.done.push(currentRoad.id);db.street.visits[currentRoad.id]={name:currentRoad.name,at:new Date().toISOString()}}save();renderStreetStats();showRoad(currentRoad)}
async function streetCatalog(){
 if(!await ensureRoads())return alert('路网尚未加载。');let d=new Set(db.street.done),arr=roads.filter(r=>!streetQuery||r.name.toLowerCase().includes(streetQuery.toLowerCase()));
 $('#view').innerHTML=`<div class="page"><div class="section-title"><div><div class="kicker">哈尔滨街道图鉴</div><h1>${d.size} / ${roads.length}</h1></div><button class="btn" id="backStreet">返回探索</button></div><div class="field"><label>搜索街道</label><input id="streetSearch" value="${esc(streetQuery)}" placeholder="例如：安发街"></div><div class="catalog-list">${arr.slice(0,300).map(r=>`<button class="catalog-row ${d.has(r.id)?'done':''}" data-road="${r.id}"><span>${d.has(r.id)?'已走':'未走'}</span><b>${esc(r.name)}</b><small>${r.lengthM<1000?Math.round(r.lengthM)+' 米':(r.lengthM/1000).toFixed(1)+' 公里'}</small></button>`).join('')||'<div class="empty">没有找到。</div>'}</div>${arr.length>300?'<p class="muted">结果较多，仅显示前 300 条；继续输入名称缩小范围。</p>':''}</div>`;
 $('#backStreet').onclick=()=>nav('street');$('#streetSearch').oninput=e=>{streetQuery=e.target.value;streetCatalog()};$$('[data-road]').forEach(b=>b.onclick=()=>{let r=roads.find(x=>x.id===b.dataset.road);nav('street');setTimeout(()=>showRoad(r),100)})
}

function story(){
 let all=[...db.stories].sort((a,b)=>String(b.updatedAt||b.createdAt).localeCompare(String(a.updatedAt||a.createdAt))),tags=[...new Set(all.flatMap(x=>x.tags||[]))],es=all.filter(e=>storyFilter==='OPEN'?!e.outcome:storyFilter==='DONE'?!!e.outcome:true).filter(e=>!storyTag||(e.tags||[]).includes(storyTag)).filter(e=>!storyQuery||[e.title,e.event,e.choice,e.outcome,e.lesson].some(v=>String(v||'').toLowerCase().includes(storyQuery.toLowerCase())));
 $('#view').innerHTML=`<div class="page"><div class="section-title"><div><div class="kicker">剧情 · 选择与结局</div><h1>人生是一场 Galgame</h1></div><button class="btn dark" id="newStory">新建剧情</button></div><div class="metric-grid"><div class="metric"><strong>${all.length}</strong><span>全部剧情</span></div><div class="metric"><strong>${all.filter(x=>x.outcome).length}</strong><span>已有结局</span></div><div class="metric"><strong>${all.filter(x=>!x.outcome).length}</strong><span>未完待续</span></div></div><div class="story-tools"><input id="storySearch" class="searchbox" value="${esc(storyQuery)}" placeholder="搜索过去的自己"><div class="filters">${[['ALL','全部'],['OPEN','未完待续'],['DONE','已有结局']].map(([v,t])=>`<button data-filter="${v}" class="${storyFilter===v?'active':''}">${t}</button>`).join('')}</div><div class="filters tagfilters"><button data-tag="" class="${!storyTag?'active':''}">全部标签</button>${tags.map(t=>`<button data-tag="${esc(t)}" class="${storyTag===t?'active':''}">#${esc(t)}</button>`).join('')}</div></div>${es.length?es.map(e=>`<article class="story-card" data-story="${e.id}"><div class="kicker">${dk(e.createdAt).replaceAll('-','.')} · ${e.outcome?'已有结局':'未完待续'}</div><h3>${esc(e.title)}</h3>${e.lesson?`<div class="lesson"><span>如果再来一次</span><br>${esc(e.lesson)}</div>`:''}<div class="tags">${(e.tags||[]).map(t=>'#'+esc(t)).join(' ')}</div></article>`).join(''):'<div class="empty">没有找到对应的剧情。</div>'}</div>`;
 $('#newStory').onclick=()=>storyForm();$('#storySearch').oninput=e=>{storyQuery=e.target.value;story()};$$('[data-filter]').forEach(b=>b.onclick=()=>{storyFilter=b.dataset.filter;story()});$$('[data-tag]').forEach(b=>b.onclick=()=>{storyTag=b.dataset.tag;story()});$$('[data-story]').forEach(x=>x.onclick=()=>storyDetail(x.dataset.story))
}
function storyForm(e=null){modal(`<h2>${e?'重写这一页':'记录一段剧情'}</h2><form id="sf" class="form"><div class="field"><label>标题</label><input name="title" required value="${esc(e?.title||'')}"></div><div class="field"><label>发生了什么？</label><textarea name="event" required>${esc(e?.event||'')}</textarea></div><div class="field"><label>当时，我做了什么选择？</label><textarea name="choice" required>${esc(e?.choice||'')}</textarea></div><div class="field"><label>后来怎么样了？</label><textarea name="outcome">${esc(e?.outcome||'')}</textarea></div><div class="field"><label>如果再来一次，我会怎么做？</label><textarea name="lesson">${esc(e?.lesson||'')}</textarea></div><div class="field"><label>标签</label><input name="tags" value="${esc((e?.tags||[]).join('，'))}"></div><div class="actions"><button class="btn dark">保存剧情</button><button type="button" class="btn" id="sx">取消</button></div></form>`);$('#sx').onclick=closeModal;$('#sf').onsubmit=x=>{x.preventDefault();let f=new FormData(x.target),now=new Date().toISOString(),o=e||{id:id(),createdAt:now};Object.assign(o,{title:f.get('title').trim(),event:f.get('event').trim(),choice:f.get('choice').trim(),outcome:f.get('outcome').trim(),lesson:f.get('lesson').trim(),tags:f.get('tags').split(/[，,]/).map(x=>x.trim()).filter(Boolean),updatedAt:now,storageType:'LOCAL'});if(!e)db.stories.push(o);save();closeModal();storyDetail(o.id)}}
function storyDetail(sid){let e=db.stories.find(x=>x.id===sid);if(!e)return nav('story');$('#view').innerHTML=`<div class="page"><button class="btn" id="storyBack">← 剧情回想</button><div class="detail-head"><div class="kicker">${dk(e.createdAt).replaceAll('-','.')} · ${e.outcome?'已有结局':'未完待续'}</div><h1 class="display">${esc(e.title)}</h1><div class="tags">${(e.tags||[]).map(t=>'#'+esc(t)).join(' ')}</div></div>${[['事件',e.event],['选择',e.choice],['结局',e.outcome||'故事还没有结束。等事情有了结果，再回来看看。'],['攻略',e.lesson||'如果再来一次，你想怎么做？']].map(([h,p])=>`<section class="chapter"><h3>${h}</h3><p>${esc(p)}</p></section>`).join('')}<div class="actions"><button class="btn dark" id="editStory">${e.outcome?'编辑':'补上结局'}</button><button class="btn danger" id="deleteStory">删除</button></div></div>`;$('#storyBack').onclick=()=>nav('story');$('#editStory').onclick=()=>storyForm(e);$('#deleteStory').onclick=()=>{if(confirm('确定删除这段剧情吗？')){db.stories=db.stories.filter(x=>x.id!==sid);save();nav('story')}}}

function eventRows(es){return `<div class="list">${es.length?es.map(e=>`<div class="row"><div class="date"><time datetime="${esc(e.at)}">${dk(e.at)}<br>${fmtTime(e.at)}</time></div><div><div class="kicker">${esc(e.type)}</div><h3>${esc(e.title)}</h3>${e.detail?`<p>${esc(e.detail)}</p>`:''}</div></div>`).join(''):'<div class="empty">还没有存档。</div>'}</div>`}
function timeline(){let es=events();$('#view').innerHTML=`<div class="page"><div class="section-title"><div><div class="kicker">同一个人 · 不同的故事</div><h1>时间线</h1></div><button class="btn dark" id="newNote">记一笔</button></div>${eventRows(es)}</div>`;$('#newNote').onclick=quickNote}
function archive(){
 $('#view').innerHTML=`<div class="page"><div class="section-title"><div><div class="kicker">本地存档</div><h1>存档管理</h1></div></div><div class="archive-box"><h3>一个文件，整个世界。</h3><p>导出内容包含行动挑战与全部成绩、街道打卡与时间、人生剧情、手记、日历待办以及应用设置。导入前会要求确认。</p><div class="actions"><button class="btn dark" id="exportAll">导出全部存档</button><label class="btn">导入统一存档<input class="file" id="importAll" type="file" accept="application/json"></label></div></div><div class="archive-box"><h3>兼容三个旧项目</h3><p>可以自动读取同一浏览器 origin 下的旧 PB、走遍哈尔滨、Galgame 数据；也可以导入三个旧项目各自导出的 JSON。</p><div class="actions"><button class="btn" id="legacyLocal">重新读取旧本地数据</button><label class="btn">导入旧项目 JSON<input class="file" id="legacyFile" type="file" accept="application/json"></label></div></div><div class="archive-box danger-zone"><h3>数据维护</h3><p>如果准备清空，请先导出完整存档。</p><button class="btn danger" id="clearAll">清空统一存档</button></div></div>`;
 $('#exportAll').onclick=exportAll;$('#importAll').onchange=importAll;$('#legacyLocal').onclick=()=>alert(migrateLegacy(true)?'已读取到旧项目数据。':'没有发现可读取的旧项目数据。');$('#legacyFile').onchange=importLegacy;$('#clearAll').onclick=()=>{if(confirm('确定清空全部统一存档？')&&confirm('最后确认：此操作无法撤销。')){db=fresh();save();nav('home')}}
}
function exportAll(){let payload={app:'SAVE POINT',format:'save-point-world',version:2,exportedAt:new Date().toISOString(),data:db},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`save-point-${dk()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importAll(e){try{let j=JSON.parse(await e.target.files[0].text());if(!j?.data||!(j.app==='SAVE POINT'||j.format==='save-point-world'))throw 0;if(confirm('用这个完整存档替换当前数据？建议先导出当前存档。')){db=normalize(j.data);save();archive()}}catch{alert('无法导入：不是有效的 SAVE POINT 存档。')}}
async function importLegacy(e){try{let j=JSON.parse(await e.target.files[0].text()),ok=false;if(Array.isArray(j.entries)){db.stories=j.entries;ok=true}else if(Array.isArray(j.challenges)){let n=normPB(j);if(n){db.pb=n;ok=true}}else if(Array.isArray(j)){db.street.done=[...new Set(j)];ok=true}else if(Array.isArray(j.done)){db.street.done=[...new Set(j.done)];ok=true}if(!ok)throw 0;save();alert('旧项目数据已导入。');archive()}catch{alert('无法识别这个旧项目 JSON。')}}
function modal(h){$('#modalCard').innerHTML=h;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()}
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();
