let memoMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1),memoSelected=null;
function validMemoDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;let d=new Date(value+'T12:00:00');return !isNaN(d)&&dk(d)===value}
function normalizeTodos(items){return Array.isArray(items)?items.filter(t=>t&&typeof t.text==='string'&&t.text.trim()&&validMemoDate(t.date)).map(t=>({id:id(),text:t.text.trim().slice(0,280),date:t.date,done:t.done===true})):[]}
function memoCalendar(ev){
 const month=dk(memoMonth).slice(0,7),today=dk(),days=new Set(ev.map(e=>dk(e.at))),blank=(memoMonth.getDay()+6)%7,n=new Date(memoMonth.getFullYear(),memoMonth.getMonth()+1,0).getDate();
 let cells='<span></span>'.repeat(blank);
 for(let i=1;i<=n;i++){let date=month+'-'+pad(i),tasks=db.todos.filter(t=>t.date===date),pending=tasks.filter(t=>!t.done).length,status=pending?(date<today?'逾期':'待办'):tasks.length?'已完成':'',label=`${date}${date===today?'，今天':''}${pending?'，'+pending+' 项'+status:status?'，'+status:''}${days.has(date)?'，有存档':''}`;cells+=`<button class="memo-day ${date===today?'is-today':''} ${date===memoSelected?'selected':''} ${pending?(date<today?'overdue':'pending'):tasks.length?'completed':''} ${days.has(date)?'has-save':''}" data-memo-date="${date}" aria-label="${label}" aria-pressed="${date===memoSelected}" title="${label}">${i}<span class="memo-mark" aria-hidden="true"></span></button>`}
 const overdue=db.todos.filter(t=>!t.done&&t.date<today).length;
 return `<section class="memo-calendar" aria-label="日历备忘"><div class="memo-heading"><span class="kicker">${memoMonth.getFullYear()} 年 ${memoMonth.getMonth()+1} 月</span><div><button id="memoPrev" aria-label="上个月">‹</button><button id="memoToday">今天</button><button id="memoNext" aria-label="下个月">›</button></div></div><div class="memo-week">${['一','二','三','四','五','六','日'].map(d=>`<span>${d}</span>`).join('')}</div><div class="memo-grid">${cells}</div><p class="memo-legend"><span>● 待办</span><span>! 逾期</span><span>✓ 完成</span></p>${overdue?`<button class="memo-overdue" id="memoOverdue">${overdue} 项逾期待办 · 点击查看</button>`:''}<div id="memoDetails">${memoSelected?memoDetails(memoSelected):'<p class="memo-hint">点击日期，查看存档或添加待办。</p>'}</div></section>`
}
function memoDetails(date){let tasks=db.todos.filter(t=>t.date===date),records=events().filter(e=>dk(e.at)===date);return `<div class="memo-detail"><h3>${date.slice(5).replace('-',' 月 ')} 日 · 备忘</h3><ul class="memo-list">${tasks.map(t=>`<li class="${t.done?'done':''}"><label><input type="checkbox" data-memo-toggle="${t.id}" ${t.done?'checked':''}><span>${esc(t.text)}<small>${t.done?'已完成':date<dk()?'逾期未完成':'待完成'}</small></span></label><button data-memo-delete="${t.id}" aria-label="删除待办：${esc(t.text)}">删除</button></li>`).join('')||'<li class="memo-hint">这一天还没有待办。</li>'}</ul><form id="memoForm"><label class="sr-only" for="memoText">添加待办</label><input id="memoText" name="text" maxlength="280" required placeholder="记下一件要做的事"><button class="btn" type="submit">添加</button></form>${records.length?`<div class="memo-records"><div class="kicker">当日存档 · ${records.length}</div>${records.map(e=>`<p>${esc(e.type)} · ${esc(e.title)}</p>`).join('')}</div>`:''}</div>`}
function bindMemoCalendar(){
 $('#memoPrev').onclick=()=>moveMemoMonth(-1);$('#memoNext').onclick=()=>moveMemoMonth(1);$('#memoToday').onclick=()=>selectMemoDate(dk());
 $$('[data-memo-date]').forEach(b=>b.onclick=()=>selectMemoDate(b.dataset.memoDate));
 if($('#memoOverdue'))$('#memoOverdue').onclick=()=>selectMemoDate(db.todos.filter(t=>!t.done&&t.date<dk()).sort((a,b)=>a.date.localeCompare(b.date))[0].date);
 $$('[data-memo-toggle]').forEach(b=>b.onchange=()=>{let t=db.todos.find(t=>t.id===b.dataset.memoToggle);t.done=b.checked;save();home();let control=$$('[data-memo-toggle]').find(x=>x.dataset.memoToggle===t.id);control?.focus()});
 $$('[data-memo-delete]').forEach(b=>b.onclick=()=>{if(confirm('删除这条待办？')){db.todos=db.todos.filter(t=>t.id!==b.dataset.memoDelete);save();home()}});
 if($('#memoForm'))$('#memoForm').onsubmit=e=>{e.preventDefault();let text=new FormData(e.target).get('text').trim();if(!text)return;db.todos.push({id:id(),date:memoSelected,text,done:false});save();home();$('#memoText').focus()}
}
function selectMemoDate(date){memoSelected=date;let d=new Date(date+'T12:00:00');memoMonth=new Date(d.getFullYear(),d.getMonth(),1);home();$$('[data-memo-date]').find(b=>b.dataset.memoDate===date)?.focus()}
function moveMemoMonth(delta){memoMonth=new Date(memoMonth.getFullYear(),memoMonth.getMonth()+delta,1);memoSelected=null;home();$(delta<0?'#memoPrev':'#memoNext').focus()}
